name: cpumodel
description: Reads and prints the CPU model from /proc/cpuinfo
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  analyzer: ^4.7.0
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  lint: ^1.8.2
  lints: ^1.0.1
  pubspec_generator: ^3.0.1
  test: ^1.21.1
